name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build CLI
      run: |
        cd rain-cli
        cargo build --verbose
    - name: Run CLI tests
      run: |
        cd rain-cli
        cargo test --verbose
    - name: Build Core
      run: |
        cd rain-core
        cargo build --verbose
    - name: Run Core tests
      run: |
        cd rain-core
        cargo test --verbose
    - name: Build GUI
      run: |
        cd rain-gui
        cargo build --verbose
    - name: Run GUI tests
      run: |
        cd rain-gui
        cargo test --verbose
    - name: Build Web
      run: |
        cd rain-web
        cargo build --verbose
    - name: Run Web tests
      run: |
        cd rain-web
        cargo test --verbose
